"""del arg_schema

Revision ID: 19fe17fb7a5f
Revises: 987505374493
Create Date: 2026-07-08 21:03:07.913850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fe17fb7a5f'
down_revision: Union[str, Sequence[str], None] = '987505374493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tool_entity', 'api_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='API 调用配置',
               existing_comment='API 调用配置(url, method, headers, body_template)',
               existing_nullable=False)
    op.drop_column('api_tool_entity', 'arg_schema')
    op.create_foreign_key(None, 'api_tool_relation', 'api_tool_entity', ['tool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_tool_relation', type_='foreignkey')
    op.add_column('api_tool_entity', sa.Column('arg_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='输入参数的 JSON Schema 定义'))
    op.alter_column('api_tool_entity', 'api_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='API 调用配置(url, method, headers, body_template)',
               existing_comment='API 调用配置',
               existing_nullable=False)
    # ### end Alembic commands ###
