"""model

Revision ID: 80e2fbd2472f
Revises: 1651d8c25d03
Create Date: 2026-07-25 19:06:10.361851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e2fbd2472f'
down_revision: Union[str, Sequence[str], None] = '1651d8c25d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_info',
    sa.Column('id', sa.String(length=36), nullable=False, comment='模型全局唯一标识符(UUID)'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='关联的用户id'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='模型图标'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='模型显示名称'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('api_key', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('desc', sa.String(length=255), nullable=False, comment='知识库描述'),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vector_store', 'update_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('vector_store', 'create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('vector_store', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展元数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('vector_store', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               comment=None,
               existing_comment='文本 embedding 向量',
               existing_nullable=True)
    op.alter_column('vector_store', 'content_tsv',
               existing_type=postgresql.TSVECTOR(),
               comment=None,
               existing_comment='全文检索向量（由 content 自动生成）',
               existing_nullable=True,
               existing_server_default=sa.Computed("to_tsvector('simple'::regconfig, COALESCE(content, ''::text))", persisted=True))
    op.alter_column('vector_store', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='片段文本内容',
               existing_nullable=True)
    op.alter_column('vector_store', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='片段在文档中的序号',
               existing_nullable=False)
    op.alter_column('vector_store', 'document_id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=36),
               comment=None,
               existing_comment='关联的文档 id',
               existing_nullable=False)
    op.alter_column('vector_store', 'library_id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=36),
               comment=None,
               existing_comment='关联的知识库 id',
               existing_nullable=False)
    op.alter_column('vector_store', 'account_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联的用户 id',
               existing_nullable=False)
    op.alter_column('vector_store', 'id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=36),
               comment=None,
               existing_comment='向量记录全局唯一标识符(UUID)',
               existing_nullable=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('store_vectors',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prefix', 'key'], ['store.prefix', 'store.key'], name=op.f('store_vectors_prefix_key_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prefix', 'key', 'field_name', name=op.f('store_vectors_pkey'))
    )
    op.create_index(op.f('store_vectors_embedding_idx'), 'store_vectors', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey'))
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('vector_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('vector_migrations_pkey'))
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    op.drop_table('model_info')
    # ### end Alembic commands ###
