"""tool

Revision ID: c324e044e520
Revises: 
Create Date: 2026-07-08 11:02:38.614661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c324e044e520'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tool_entity',
    sa.Column('id', sa.String(length=36), nullable=False, comment='工具全局唯一标识符(UUID)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具内部调用名(如 get_weather)'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='工具显示名称(如 获取天气)'),
    sa.Column('desc', sa.Text(), nullable=False, comment='工具描述(给大模型看的)'),
    sa.Column('arg_schema', sa.JSON(), nullable=False, comment='输入参数的 JSON Schema 定义'),
    sa.Column('api_config', sa.JSON(), nullable=False, comment='API 调用配置(url, method, headers, body_template)'),
    sa.Column('createBy', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('updateBy', sa.Integer(), nullable=False, comment='更新人'),
    sa.Column('createAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updateAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tool_entity_name'), 'api_tool_entity', ['name'], unique=True)
    op.create_table('api_tool_relation',
    sa.Column('account_id', sa.Integer(), nullable=False, comment='所属账户ID'),
    sa.Column('tool_id', sa.String(length=36), nullable=False, comment='关联的工具id'),
    sa.Column('createAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updateAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tool_id'], ['api_tool_entity.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'tool_id')
    )
    op.create_index(op.f('ix_api_tool_relation_account_id'), 'api_tool_relation', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_tool_relation_tool_id'), 'api_tool_relation', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tool_relation_tool_id'), table_name='api_tool_relation')
    op.drop_index(op.f('ix_api_tool_relation_account_id'), table_name='api_tool_relation')
    op.drop_table('api_tool_relation')
    op.drop_index(op.f('ix_api_tool_entity_name'), table_name='api_tool_entity')
    op.drop_table('api_tool_entity')
    # ### end Alembic commands ###
