server {
    listen 80;
    client_max_body_size 100m;

    # /cos/uploads/a.txt -> https://<bucket>/uploads/a.txt
    location /cos/ {
        proxy_pass https://llmops-1258847722.cos.ap-chongqing.myqcloud.com/;
        proxy_set_header Host llmops-1258847722.cos.ap-chongqing.myqcloud.com;
        proxy_ssl_server_name on;
        proxy_request_buffering off;
    }

    location / {
        return 404;
    }
}
